https://numpy.org/doc/stable/reference/index.html 

In [2]:
import numpy as np

# Array shape

In [3]:
xs = np.array([1,10])

In [4]:
xs

array([ 1, 10])

In [5]:
type(xs)

numpy.ndarray

In [6]:
# Pay attention to this one
xs.shape

(2,)

In [7]:
xs = np.array([1,10])

In [8]:
xs

array([ 1, 10])

In [9]:
xs[0]

1

In [10]:
xs[1]

10

In [15]:
ys = np.array([[1,10]])

In [12]:
ys

array([[ 1, 10]])

In [16]:
type(ys)

numpy.ndarray

In [17]:
# The shape of ys is different from the shape of xs!
ys.shape

(1, 2)

In [18]:
ys[0]

array([ 1, 10])

In [19]:
ys[0][0]

1

In [20]:
ys[0][1]

10

In [21]:
# How to convert a 2-D Numpy array into 1-D
length_1d = ys.shape[0]*ys.shape[1]
zs = np.reshape(ys,length_1d)

In [22]:
zs.shape

(2,)

In [28]:
# How to convert a 2-D Numpy array into 1-D: '-1' means autofill the length
zs = np.reshape(ys,-1)

In [29]:
zs.shape

(2,)

In [30]:
ws = np.reshape(xs,(1,2))
ws

array([[ 1, 10]])

In [31]:
ws.shape

(1, 2)

In [32]:
ws = np.reshape(xs,(2,1))
ws

array([[ 1],
       [10]])

In [33]:
ws.shape

(2, 1)

In [34]:
ws = np.reshape(xs,(1,-1))
ws

array([[ 1, 10]])

In [36]:
ws.shape

(1, 2)

In [ ]:
# element-wise equal
ws == ys

In [ ]:
# array equal
np.array_equal(ws,ys)

# Matrix operation

In [37]:
A = np.array([[1,1,0], [0,1,-1], [1,1,1]])
A

array([[ 1,  1,  0],
       [ 0,  1, -1],
       [ 1,  1,  1]])

In [38]:
np.transpose(A)

array([[ 1,  0,  1],
       [ 1,  1,  1],
       [ 0, -1,  1]])

In [39]:
A.T

array([[ 1,  0,  1],
       [ 1,  1,  1],
       [ 0, -1,  1]])

In [40]:
x = np.array([2,1,3])
x

array([2, 1, 3])

In [41]:
x = np.array([2,1,3]).reshape((3,1))
x

array([[2],
       [1],
       [3]])

In [42]:
A*x

array([[ 2,  2,  0],
       [ 0,  1, -1],
       [ 3,  3,  3]])

In [43]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [44]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])