# 运算

In [1]:
2 + 3

5

In [2]:
2 * 3

6

In [3]:
2 ** 3

8

In [4]:
2 / 3

0.6666666666666666

In [5]:
2 <= 3

True

In [6]:
2 == 3

False

In [7]:
2 != 3

True

In [8]:
(2 < 3) and (3 < 2)

False

In [9]:
(2 < 3) or (3 < 2)

True

# 字符串

In [10]:
'hello world'

'hello world'

In [11]:
"hello world"

'hello world'

In [12]:
'hello world' == "hello world"

True

In [13]:
print('hello world')

hello world


In [14]:
print('hello \'world\'')

hello 'world'


In [15]:
s = 'hello world'

In [16]:
s[3]

'l'

In [17]:
s[0:3]

'hel'

In [18]:
s[1:3]

'el'

In [19]:
s[3:]

'lo world'

In [20]:
s[-3:]

'rld'

In [21]:
a='错误的
多行文本'
print(a) # You will see a SyntaxError

SyntaxError: EOL while scanning string literal (2838636054.py, line 1)

In [22]:
a='''正确的
多行文本'''
print(a)

正确的
多行文本


In [23]:
print('换行\n换行')

换行
换行


# List

In [24]:
xs = [1,2,3,4,5]

In [25]:
xs[0]

1

In [26]:
xs[4]

5

In [27]:
xs[1:4] # 左闭右开

[2, 3, 4]

In [28]:
xs[3:]

[4, 5]

# Tuple

In [29]:
xs_list = [1,2,3,4,5]
type(xs_list)

list

In [30]:
xs_tuple = (1,2,3,4,5)
type(xs_tuple)

tuple

In [31]:
xs_tuple[0]

1

In [32]:
xs_tuple[3:]

(4, 5)

In [33]:
xs_list[0] = 100
xs_list

[100, 2, 3, 4, 5]

In [34]:
xs_tuple[0] = 100
xs_tuple # You will see a TypeError

TypeError: 'tuple' object does not support item assignment

# 注释

In [36]:
a = 1 # 这是注释

In [37]:
# 这也是注释
a = 1

In [38]:
a = 1

'''
三个单引号也可用来写长注释
a = 2
'''

print(a)

1


# Dictionaries

In [39]:
a = {
    'length': 1,
    'height': 2,
    'weight': 3,
    'hello world': 4
}
a

{'length': 1, 'height': 2, 'weight': 3, 'hello world': 4}

In [40]:
a['length']

1

In [41]:
a['hello world']

4

In [42]:
a.keys()

dict_keys(['length', 'height', 'weight', 'hello world'])

# Import packages

In [43]:
import numpy
numpy.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
import numpy as np
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [45]:
from numpy import linspace
linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Built-in functions

In [46]:
xs = [101,102,103]
len(xs)

3

In [47]:
type(xs)

list

In [48]:
xs = [101,102,103]
n = len(xs)
for i in range(n):
    print(i, xs[i])

0 101
1 102
2 103


In [49]:
range(5)

range(0, 5)

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

# 函数

In [51]:
def add(a, b):
    """Add stuff.

    a - something that can be addded
    b - something that can be added

    Returns a + b
    """
    ans = a + b
    return ans

In [52]:
help(add)

Help on function add in module __main__:

add(a, b)
    Add stuff.
    
    a - something that can be addded
    b - something that can be added
    
    Returns a + b



In [53]:
x = 2
y = 3
add(x, y)

5

In [54]:
[1,23] + [6,7,8]

[1, 23, 6, 7, 8]

In [55]:
add([1,23], [6,7,8])

[1, 23, 6, 7, 8]

In [56]:
def f(a,b,c):
    return c,b,a

In [57]:
f(1,2,3)

(3, 2, 1)

In [58]:
f_output = f(1,2,3)
type(f_output)

tuple

In [59]:
f(a=1,b=2,c=3)

(3, 2, 1)

In [60]:
f(c=3,b=2,a=1)

(3, 2, 1)

## 函数的默认参数

In [61]:
def f_default(a=10,b=20,c=30):
    return c,b,a

In [62]:
f_default()

(30, 20, 10)

In [63]:
f_default(100)

(30, 20, 100)

In [64]:
f_default(c = 100)

(100, 20, 10)

## Variadic arguments

In [65]:
def f_v(a, *args):
    return a, args

In [66]:
f_v(1)

(1, ())

In [67]:
f_v(1,2)

(1, (2,))

In [68]:
f_v(1,2,3)

(1, (2, 3))

In [69]:
f_v(1,name='Alice',age=5) # You will see a TypeError

TypeError: f_v() got an unexpected keyword argument 'name'

In [70]:
def f_v2(a, *args, **kwargs):
    return a, args, kwargs

### 位置参数和关键字参数
位置参数 (Positional Arguments)：指根据参数的位置来传递的参数。在调用函数时，位置参数的值按照定义顺序依次赋值给函数的参数。
```PYTHON
def example(a, b, c):
    print(a, b, c)

example(1, 2, 3)  # 输出：1 2 3
```
在上面的例子中，1 赋值给 a，2 赋值给 b，3 赋值给 c，都是根据位置传递的。

关键字参数 (Keyword Arguments)：指在调用函数时，直接通过参数名称指定值。关键字参数不依赖顺序，而是通过参数名来传递。
```PYTHON
def example(a, b, c):
    print(a, b, c)

example(a=1, c=3, b=2)  # 输出：1 2 3
```

在上面的例子中，a=1，b=2，c=3，通过参数名指定值的传递。

### *args 和 **kwargs 的作用
*args：用于接收不定数量的位置参数，并将它们存储在一个元组中。
```PYTHON
def example(*args):
    print(args)

example(1, 2, 3)  # 输出：(1, 2, 3)
```

这里 args 是 (1, 2, 3)，表示接收的所有位置参数被收集到一个元组中。

**kwargs：用于接收不定数量的关键字参数，并将它们存储在一个字典中。
```PYTHON
def example(**kwargs):
    print(kwargs)

example(a=1, b=2, c=3)  # 输出：{'a': 1, 'b': 2, 'c': 3}
```
这里 kwargs 是 {'a': 1, 'b': 2, 'c': 3}，表示接收的所有关键字参数被收集到一个字典中。

In [71]:
f_v2(1,2,3)

(1, (2, 3), {})

In [72]:
f_v2(1,name='Alice',age=5)

(1, (), {'name': 'Alice', 'age': 5})

In [73]:
f_v2(1,2,3,name='Alice',age=5)

(1, (2, 3), {'name': 'Alice', 'age': 5})

# 对象

In [74]:
class A: # 类（class）
    """Class A"""
    def __init__(self, x):
        self.x = x

    def __repr__(self):
        return '{}({})'.format(self.__class__.__name__, self.x)

    def report(self):
        return self.x
    
    def increase(self,increasement = 1):
        self.x = self.x + increasement
        return self.x
    
    def silent_increase(self,increasement = 1):
        self.x = self.x + increasement

class B(A):
    """Class B inherits from A."""
    def __init__(self, x, y):
        self.y = y
        # super() returns the first parent class with the a method called __init__
        super().__init__(x)

    def report(self):
        """Over-ridden method."""
        return self.x, self.y

In [75]:
a = A(1) # a是类A的一个实体（instance）
b = B(2,3)

In [76]:
a, b # This uses the ``__repr__`` method found only in A

(A(1), B(2))

In [77]:
a.report() # report()是类A的所有实体均具有的方法（method）

1

In [78]:
b.report()

(2, 3)

In [79]:
a.x # x是类A的所有实体均具有的属性（attribute）

1

In [80]:
a.increase()

2

In [81]:
a.increase(10)

12

In [82]:
a.x

12

In [83]:
a.silent_increase()

In [84]:
a.x

13

In [85]:
# class attributes and methods
A.__class__.__name__

'type'

In [86]:
# instance attributes and methods
a.__class__.__name__

'A'

### Special methods

such as 
```
__init__, __repr__.
```
https://diveintopython3.net/special-method-names.html